apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sta7r7sdg-nodejs 
  janus-idp.io/tekton: sta7r7sdg-nodejs
  backstage.io/kubernetes-id: sta7r7sdg-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sta7r7sdg-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  